server:
  port: 8761
eureka:
  instance:
    hostname: ${DISCOVERY_HOST_NAME:localhost}
    preferIpAddress: ${DISCOVERY_PREFER_IP:true}
    securePortEnabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URI:http://localhost:8761/eureka}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    renewalPercentThreshold: ${DISCOVERY_RENEW_THRESHOLD:0.49}
    renewalThresholdUpdateIntervalMs: ${DISCOVERY_RENEW_THRESHOLD_PERIOD:30000}
  
logging:
  level:
    ROOT: WARN
    com.tavant.finexp: INFO
---
spring:
    profiles: dev
logging:
  level:
    ROOT: INFO
    com.tavant.finexp: DEBUG
---
spring:
    profiles: qa
logging:
  level:
    ROOT: INFO
    com.tavant.finexp: DEBUG    
